static const char *fragment_shaders[Prog_COUNT+2] = {
"void main(){"
"vec2 uv=floor(gl_FragCoord.xy)/4096.;"
"float height=fbm(uv,5.);"
"height=pow(height,3.)*1200.;"
"gl_FragColor=vec4(0.,0.,height,0.);"
"}"
, 
"float\n"
"Kr=.27,"
"Ke=.005,"
"Ks=.8;"
"vec2 uv=floor(gl_FragCoord.xy);"
"float tf(float H,float w,vec2 o){"
"vec4 c=TT(uv+o);"
"float h=c.w+c.z,d=H-h;"
"return mix(-min(w,d),min(c.w,-d),step(d,.0));"
"}"
"void main(){"
"vec4 c=TT(uv);"
""
""
"vec4 c0=c;"
"float h=c.w+c.z,dw=0.;"
"vec3 e=vec3(1.,0.,-1.);"
"float kk=.25;"
"dw+=kk*tf(h,c.w,e.xy);"
"dw+=kk*tf(h,c.w,e.yx);"
"dw+=kk*tf(h,c.w,-e.xy);"
"dw+=kk*tf(h,c.w,-e.yx);"
""
""
""
""
""
"c.w+=dw;"
""
""
"dw=c.w*Ke;"
"c.z+=dw*Ks;"
"c.w-=dw;"
""
"float sa=sin(_t*373.4111),ca=cos(_t*373.4111);"
"mat2 m=mat2(sa,ca,ca,-sa);"
"dw=Kr*n4((uv+vec2(_t*123.24,317.1141*_t))*m).x*(0==mod(floor(_t/3.),12.)?.1:.0);"
""
"c.z-=dw*Ks;"
"c.w+=dw;"
""
"gl_FragColor=vec4("
"1000.*(c.w-c0.w),"
"-1000.*(c.z-c0.z),"
"c.z,"
"c.w);"
"}"
, 
"void main(){"
"vec2 p=fc*32.;"
"float h=1e6,H=0.;"
"for(int x=0;x<32;++x){"
"for(int y=0;y<32;++y){"
"vec2 P=p+vec2(float(x),float(y));"
"vec4 s=TT(P);"
"H=max(H,s.z);h=min(h,s.z);"
"}"
"}"
"float d=H-h;"
"vec4 r=n4(fc);"
"float pop=pow(smoothstep(25.,0.,d)*smoothstep(230.,110.,H),14.);"
"pop*=.2+.8*r.z;"
"pop+=step(0.,pop)*.08;"
"gl_FragColor=vec4(r.y,max(0.,pop*90.)+H,h,H);"
"}"
, 
"const float EPS=.01,FAR=5000.,SKY=FAR,GS=32.;"
""
"vec3 sundir=normalize(_s);"
""
"float H(vec2 p){vec4 c=TT(p);return c.z;}"
""
"vec3 TN(vec2 p){"
"vec2 e=vec2(1.,.0);"
"vec3 dx=vec3(2.*e.x,H(p+e.xy)-H(p-e.xy),0.);"
"vec3 dz=vec3(0.,H(p+e.yx)-H(p-e.yx),2.*e.x);"
""
"return normalize(cross(dz,dx)+3.5*(n4(p*7.31).yxz-vec3(.5)));"
"}"
""
"float maxv(vec3 v){return max(v.x,max(v.y,v.z));}"
"float dbox(vec3 p,vec3 sz){"
"return maxv(abs(p)-sz);"
"}"
""
"float TD(vec3 p,vec3 D){"
"float H=H(p.xz);"
"return(p.y-H);"
"}"
""
""
""
""
""
""
""
""
""
""
"float TB(vec3 O,vec3 D,float e,float lo,float li){"
"for(int i=0;i < 8;++i){"
"float lm=(lo+li)*.5;"
"if(TD(O+D*lm,D)< e)li=lm;else lo=lm;"
"}"
"return lo;"
"}"
""
"struct cell_t{"
"vec2 i;"
"vec3 c,m,M,BB;"
"vec4 S;"
"float B,H,h,p,Bh,f;"
"};"
""
"cell_t CI(vec3 p){"
"cell_t c;"
"c.i=floor(p.xz/GS);"
"c.m=c.i.xyy*GS;"
"vec4 P=PP(c.m.xz);c.p=P.x;"
"c.B=P.y;c.H=P.w;c.h=P.z;c.Bh=c.B-c.H;"
"c.m.y=c.h;"
"c.M=c.m+vec3(GS,c.B,GS);"
"c.c=c.m+vec3(GS,c.H-c.h,GS)*.5;"
"c.S=n4(c.i+vec2(23.,17.)).wyzx;"
"c.BB=vec3(GS*.5-4.,c.Bh,GS*.5-4.);"
"c.f=9.+.2*c.S.y;"
"return c;"
"}"
""
"float bd1(vec3 p,cell_t c){"
"vec2 e=vec2(1.,0.);"
"float d=1e6;"
"vec3 s=c.BB*vec3(.2+.3*c.S.z,1.,.2+.3*c.S.y);"
"for(int i=0;i < 4;++i)"
"{"
"vec3 pp=p-(c.BB-s)*(2.*vec3(c.S.w,0.,c.S.z)-vec3(1.));"
"d=min(d,dbox(pp,s));"
"s+=vec3(.2+c.S.x,0.,.2+c.S.y)*.2*c.BB;"
"s.y*=.7+.1*c.S.z;"
"}"
"return d;"
"}"
""
"float BD(vec3 p,cell_t c){"
"p-=c.c;"
"float d=(c.Bh < 10.)? 1e6 : bd1(p,c);"
"return max(d,dbox(p,c.BB));"
"}"
""
"vec3 block_normal(vec3 p,cell_t c){"
"vec2 e=vec2(.01,.0);"
"return normalize(vec3("
"BD(p+e.xyy,c)-BD(p-e.xyy,c),"
"BD(p+e.yxy,c)-BD(p-e.yxy,c),"
"BD(p+e.yyx,c)-BD(p-e.yyx,c)"
"));"
"}"
""
"struct hit_t{"
"int mid;"
"float l;"
"vec3 p,i,n;"
"cell_t c;"
"float _gc,_mc;"
"};"
""
"hit_t BH(hit_t h){"
"h.mid=2;"
"h.n=block_normal(h.p,h.c);"
"return h;"
"}"
""
"hit_t TH(hit_t h){"
"h.mid=(h.c.Bh > 10.)? 3 : 1;"
"h.n=TN(h.p.xz);"
"return h;"
"}"
""
""
""
""
""
""
""
""
"float xp(float o,float d,float m,float M){"
"if(abs(d)< 1e-6)return 1e6;"
"return((d>0.)?(M-o):(m-o))/ d;"
"}"
""
"hit_t RT(vec3 O,vec3 D,float Lmax){"
"hit_t h;"
"h.mid=-1;"
"h.l=0.;"
"h.i=D;"
"h._gc=h._mc=0.;"
"float dl=0.;"
"float pl=h.l;"
"for(int i=0;i < 256;++i){"
"if(h.l > Lmax)break;"
"float de=EPS*h.l*2e-2;"
"h.p=O+D*h.l;"
"if(dl < 0.|| h.p.y > h.c.B){"
"h._gc+=1.;"
"h.l+=max(0.,dl)+EPS;"
"h.p=O+D*h.l;"
"h.c=CI(h.p);"
""
""
""
"float dx=xp(h.p.x,D.x,h.c.m.x,h.c.m.x+GS);"
"float dz=xp(h.p.z,D.z,h.c.m.z,h.c.m.z+GS);"
""
""
""
""
"float dy="
"(h.p.y > h.c.B)?"
"xp(h.p.y,D.y,h.c.B,SKY):"
"((h.p.y > h.c.H)?"
"xp(h.p.y,D.y,h.c.H,h.c.B):"
"1e6);"
""
"dl=min(dx,min(dy,dz));"
""
"dl+=EPS;"
""
"}else\n"
""
"{"
"h._mc+=1.;"
"float d=BD(h.p,h.c);"
"if(d < de)return BH(h);"
"if(h.p.y < h.c.H)"
"{"
"d=min(d,TD(h.p,D));"
"if(d < de){"
"h.l=TB(O,D,de,pl,h.l);"
"h.p=O+D*h.l;"
"return TH(h);"
"}"
"}"
"d=min(d,dl+EPS);"
"dl-=d;"
"pl=h.l;"
"h.l+=d;"
"}"
"}"
"return h;"
"}"
""
"struct mat_t{"
"vec3 e,Cd,Cs;"
"float s;"
"};"
""
"vec3 mg(vec2 p){"
"return vec3(.2,.6,.23)*.3+.1*(n4(p*.2).xxx-vec3(.5));"
"}"
""
"mat_t M(hit_t h){"
"mat_t m;"
"m.e=vec3(1.,0.,1.);"
"m.Cd=vec3(0.);"
"m.Cs=vec3(0.);"
"m.s=0.;"
"vec3 cp=abs(abs(h.p-h.c.c)-vec3(GS,0.,GS)*.5);"
""
"if(h.mid==1){"
"float f=step(h.p.y+h.c.S.w*50.+20.*n4(h.p.xz).x,180.);"
"m.e=vec3(0.);"
"m.Cd=mg(h.p.xz)+vec3(.1,.1,.02)*h.c.S.xyz*f;"
"m.Cd=mix(m.Cd,vec3(.11,.07,.03),.4*f*step(min(cp.x,cp.z),1.));"
""
"}else{"
"if(h.mid==2){"
"m.e=vec3(0.);"
"vec3 wn=floor(h.p);"
"if(mod(wn,vec3(3.))==vec3(0.)){"
"m.e=10.*(vec3(.6)+.2*(n4(wn.yz).wzy+n4(wn.xx).xwz))*step(1.1,n4(wn.xy).x+n4(wn.zz).z);"
"}"
"m.Cd=vec3(.2)+.2*h.c.S.x+.1*h.c.S.ywz;"
"}else{"
"if(h.mid==3){"
"m.e=vec3(0.);"
"m.Cd=mix(mg(h.p.xz),vec3(.1),step(min(cp.x,cp.z),2.));"
"m.Cs=vec3(.3);"
""
"}}}"
"return m;"
"}"
""
"vec3 brdf(hit_t h,mat_t m,vec3 wi){"
"vec3 wo=-h.i,wh=normalize(wi+wo);"
"float ci=max(0.,dot(h.n,wi)),co=max(0.,dot(h.n,wo)),ch=dot(wi,wh);"
""
"return "
".3875077*m.Cd*(vec3(1.)-m.Cs)*(1.-pow(1.-.5*ci,5.))*(1.-pow(1.-.5*co,5.))"
""
""
";"
"}"
""
"vec3 ref(hit_t h){"
"vec3 r=rand().zyx*2.-vec3(1.);"
"return normalize(r*sign(dot(r,h.n)));"
"}"
""
"vec3 air(vec3 O,vec3 D){"
"return 30.*vec3(1.)*smoothstep(.999,.9999,dot(D,sundir))"
"+pow("
"vec3(128.,218.,235.)/255."
",vec3(2.2));"
"}"
""
""
""
""
""
""
""
"void main(){"
""
"vec2 res=vec2(1920.,1080.);"
"vec2 uv=gl_FragCoord.xy/res-vec2(.5);uv.x*=res.x/res.y;"
"vec3 O=_cp,D=normalize(vec3(uv,2.))*_cm;"
""
""
""
"O+=n4(vec2(_t)*gl_FragCoord.xy).xyz*vec3(.3,.3,.3);"
""
"vec3 color=vec3(0.),ct=vec3(1.);"
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
"float Lmax=FAR;"
"for(int i=0;i < 3;++i){"
"if(dot(ct,ct)<.001)break;"
"hit_t h=RT(O,D,Lmax);"
""
""
"if(h.mid > 0){"
"mat_t m=M(h);"
"vec3 c=m.e;"
"O=h.p+h.n*EPS;"
""
"if(RT(O,sundir,100.).l >=100.)c+=brdf(h,m,sundir)*air(O,sundir);"
"D=ref(h);"
"color+=ct*c;"
"ct*=brdf(h,m,D);"
"Lmax*=.6;"
"}else{"
"color+=ct*air(O,D);"
"}"
"}"
""
""
"gl_FragColor=vec4(color,1.);"
"}"
, 
"void main(){"
"vec2 uv=fc/_r;"
"gl_FragColor=mix("
"vec4(mix(0.,step(uv.x,_p),step(uv.y,.025))),"
"pow(texture2D(_F,uv,-20.)/64.,vec4(1./2.2)),"
"step(1.,_p)"
");"
"}"
, 
"uniform float _t,_p;"
"uniform vec2 _r;"
"uniform vec3 _s,_cp;"
"uniform mat3 _cm;"
"uniform sampler2D _N,_T,_P,_F;"
"varying vec2 V;"
"vec2 fc=floor(gl_FragCoord.xy);"
"vec4 n4(vec2 v){return texture2D(_N,(v+vec2(.5))/256.,-20.);}"
"float n(vec2 v){return n4(v).w;}"
"float vn(vec2 v,vec2 m){"
"vec2 e=vec2(1.,0.),V=floor(v);v=fract(v);v*=v*(3.-2.*v);"
"return mix(mix(n(mod(V+e.yy,m)),n(mod(V+e.xy,m)),v.x),mix(n(mod(V+e.yx,m)),n(mod(V+e.xx,m)),v.x),v.y);"
"}"
"float fbm(vec2 v,float s){"
"float r=0.,k=.5;"
"for(int i=0;i<12;++i,k*=.5,s*=2.)r+=k*vn(v*s,vec2(s));"
"return r;"
"}"
"int rs=int(fc.y*1280.+fc.x)+int(n4(vec2(_t,0.)).x*256.+n4(vec2(0.,_t)).z)*256;"
"vec4 rand(){rs=int(mod(float(rs+1),1024.*1024.));return n4(vec2(float(rs),floor(float(rs)/1024.)));}"
"vec4 TT(vec2 p){return texture2D(_T,(p+vec2(.5))/4096.,-20.);}"
"vec4 PP(vec2 p){return texture2D(_P,(floor(p/32.)+vec2(.5))/128.,-20.);}", 
};
