static const char *fragment_shaders[Prog_COUNT+1] = {
"void main(){"
"vec2 uv=fc/4096.;"
"float h=fbm(uv,5.);"
"h=pow(h,3.)*1200.;"
"gl_FragColor=vec4(0.,0.,h,0.);"
"}"
, 0
, 
"void main(){"
"vec2 p=fc*32.;"
"float h=1e6,H=0.;"
"for(int x=0;x<32;++x){"
"for(int y=0;y<32;++y){"
"vec2 P=p+vec2(float(x),float(y));"
"vec4 s=TT(P);"
"H=max(H,s.z);h=min(h,s.z);"
"}"
"}"
"float d=H-h;"
"vec4 r=n4(fc);"
"float pop=pow(smoothstep(25.,0.,d)*smoothstep(230.,110.,H),14.);"
"pop*=.2+.8*r.z;"
"pop+=step(0.,pop)*.08;"
"gl_FragColor=vec4(r.y,max(0.,pop*90.)+H,h,H);"
"}"
, 
"const float EPS=.01,FAR=5000.,SKY=FAR,GS=32.;"
""
"float Mv(vec3 v){return max(v.x,max(v.y,v.z));}"
"float bx(vec3 p,vec3 sz){"
"return Mv(abs(p)-sz);"
"}"
""
""
"float H(vec2 p){vec4 c=TT(p);return c.z "
""
"+.5*n4(p).z*step(.5,n4(p*.17).w)"
""
"+4.*n4(p*.3).z*step(.6,n4(p*.02).w)"
";}"
"float TD(vec3 p,vec3 D){"
"return p.y-H(p.xz);"
"}"
"vec3 TN(vec2 p){"
"vec2 e=vec2(.01,.0);"
"vec3 dx=vec3(2.*e.x,H(p+e.xy)-H(p-e.xy),0.);"
"vec3 dz=vec3(0.,H(p+e.yx)-H(p-e.yx),2.*e.x);"
""
"return normalize(cross(dz,dx)+.001*(n4(p*7.31).yxz-vec3(.5)));"
"}"
""
""
""
""
""
""
""
""
""
""
"float TB(vec3 O,vec3 D,float e,float lo,float li){"
"for(int i=0;i < 8;++i){"
"float lm=(lo+li)*.5;"
"if(TD(O+D*lm,D)< e)li=lm;else lo=lm;"
"}"
"return lo;"
"}"
""
"struct cell_t{"
"vec2 i;"
"vec3 c,m,M,BB;"
"vec4 S;"
"float B,H,h,p,Bh,f;"
"};"
"cell_t c;"
""
"int hm;"
"float hl;"
"vec3 hp,hi,hn;"
""
""
"vec3 Ce,Cd,Cs;"
""
"void CI(vec3 p){"
"c.i=floor(p.xz/GS);"
"c.m=c.i.xyy*GS;"
"vec4 P=PP(c.m.xz);c.p=P.x;"
"c.B=P.y;c.H=P.w;c.h=P.z;c.Bh=c.B-c.H;"
"c.m.y=c.h;"
"c.M=c.m+vec3(GS,c.B,GS);"
"c.c=c.m+vec3(GS,c.H-c.h,GS)*.5;"
"c.S=n4(c.i+vec2(23.,17.)).wyzx;"
"c.BB=vec3(GS*.5-4.,c.Bh,GS*.5-4.);"
"c.f=9.+.2*c.S.y;"
"}"
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
"float BD(vec3 p){"
"p-=c.c;"
"if(c.Bh < 10.)return 1e6;"
""
"vec2 e=vec2(1.,0.);"
"float d=1e6;"
"vec3 s=c.BB*vec3(.4+.3*c.S.z,1.,.4+.3*c.S.y);"
"for(int i=0;i < 4;++i)"
"{"
"vec3 pp=p-(c.BB-s)*(2.*vec3(c.S.w,0.,c.S.z)-vec3(1.));"
"d=min(d,bx(pp,s));"
"s+=vec3(.2+c.S.x,0.,.2+c.S.y)*.2*c.BB;"
"s.y*=.7+.1*c.S.z;"
"}"
"return max(d,bx(p,c.BB));"
"}"
""
"vec3 BN(vec3 p){"
"vec2 e=vec2(.01,.0);"
"return normalize(vec3("
"BD(p+e.xyy)-BD(p-e.xyy),"
"BD(p+e.yxy)-BD(p-e.yxy),"
"BD(p+e.yyx)-BD(p-e.yyx)"
"));"
"}"
""
""
"vec3 mg(vec2 p){"
"return vec3(.2,.6,.23)*.3+.2*(n4(p*.2).xxx-vec3(.5));"
"}"
""
"void BH(){"
"hm=1;"
"vec3 wn=floor(hp);"
"if(mod(wn,vec3(3.))==vec3(0.))"
"Ce=10.*(vec3(.6)+.2*(n4(wn.yz).wzy+n4(wn.xx).xwz))*step(1.1,n4(wn.xy).x+n4(wn.zz).z);"
"else "
"Ce=vec3(0.);"
"Cd=vec3(.2)+.2*c.S.x+.1*c.S.ywz;"
""
"hn=BN(hp);"
"}"
""
"void TH(){"
"hm=1;"
"vec3 cp=abs(abs(hp-c.c)-vec3(GS,0.,GS)*.5);"
"if(c.Bh < 10.){"
"float f=step(hp.y+c.S.w*50.+20.*n4(hp.xz).x,180.);"
""
"Cd=mg(hp.xz)+vec3(.1,.1,.02)*c.S.xyz*f;"
"Cd=mix(Cd,vec3(.11,.07,.03),.4*f*step(min(cp.x,cp.z),1.));"
"}else{"
""
"Cd=mix(mg(hp.xz),vec3(.1),step(min(cp.x,cp.z),2.));"
""
""
"Ce="
"(vec3(1.,1.,.4)*step(.92,n4(cp.xz).z)"
"+vec3(1.,0.,0.)*step(.92,n4(cp.xz).y))"
"*step(min(cp.x,cp.z),2.)*3.;"
""
""
"}"
"hn=TN(hp.xz);"
"}"
""
""
""
""
""
""
""
""
"float xp(float o,float d,float m,float M){"
"if(abs(d)< 1e-6)return 1e6;"
"return((d>0.)?(M-o):(m-o))/ d;"
"}"
""
"float RT(vec3 O,vec3 D,float L){"
"hm=-1;"
"hl=0.;"
"hi=D;"
"float dl=0.,pl=hl,de,dx,dy,dz,d;"
"for(int i=0;i < 256;++i){"
"if(hl > L)break;"
"float de=EPS*hl*2e-2;"
"hp=O+D*hl;"
"if(dl < 0.|| hp.y > c.B){"
"hl+=max(0.,dl)+EPS;"
"hp=O+D*hl;"
"CI(hp);"
""
""
""
"dx=xp(hp.x,D.x,c.m.x,c.m.x+GS);"
"dz=xp(hp.z,D.z,c.m.z,c.m.z+GS);"
""
""
""
""
"dy="
"(hp.y > c.B)?"
"xp(hp.y,D.y,c.B,SKY):"
"((hp.y > c.H)?"
"xp(hp.y,D.y,c.H,c.B):"
"1e6);"
""
"dl=min(dx,min(dy,dz));"
""
"dl+=EPS;"
""
"}else "
""
"{"
"d=BD(hp);"
"if(d < de){BH();break;}"
"if(hp.y < c.H)"
"{"
"d=min(d,TD(hp,D));"
"if(d < de){"
"hl=TB(O,D,de,pl,hl);"
"hp=O+D*hl;"
"TH();break;"
"}"
"}"
"d=min(d,dl+EPS);"
"dl-=d;"
"pl=hl;"
"hl+=d;"
"}"
"}"
"return hl;"
"}"
""
"vec3 brdf(vec3 wi){"
"vec3 wo=-hi,wh=normalize(wi+wo);"
"float ci=max(0.,dot(hn,wi)),co=max(0.,dot(hn,wo)),ch=dot(wi,wh);"
""
"return "
".3875077*Cd*(vec3(1.)-Cs)*(1.-pow(1.-.5*ci,5.))*(1.-pow(1.-.5*co,5.))"
""
""
";"
"}"
""
"vec3 ref(){"
""
"vec3 r=n4(fc+floor(hp.zy*313.)).zyx+n4(floor(hp.zx*171.)-fc).wxy-vec3(1.);"
"return normalize(r*sign(dot(r,hn)));"
"}"
""
"const float I=10.,g=.76,g2=g*g,R0=6360e3,R1=6420e3;"
"const vec3 C=vec3(0.,-R0,0.),Km=vec3(21e-6),Kr=vec3(5.8,13.5,33.1)*1e-6;"
""
"float ER(vec3 o,vec3 d,float r){"
"o-=C;"
"float "
"b=dot(o,d),"
"c=dot(o,o)-r*r,"
"e=b*b-c,"
"p,q;"
"if(e < 0.)return-1.;"
"e=sqrt(e);"
"p=-b-e,"
"q=-b+e;"
"return(p >=0.)? p : q;"
"}"
""
"vec2 SD(vec3 O){"
"float h=R0-length(O-C);"
"return vec2(exp(h / 120.),exp(h / 8000.));"
"}"
""
"vec2 Id(vec3 O,vec3 D,float L){"
"float dx,bdx=L / 16.,l=0.;"
"vec3 p=O;"
"vec2 mr=vec2(0.);"
"for(int i=0;i < 16;++i){"
"dx=bdx*(1.+n4(p.xz*2e3).w);"
"p=O+D*(l+dx);"
"mr+=SD(p)*dx;"
"l+=bdx;"
"}"
"return mr;"
"}"
""
"vec3 S(vec3 O,vec3 D,float L,vec3 cc){"
"float c=max(0.,dot(D,_s)),"
"Pr=.0596831*(1.+c*c),"
"Pm=.1193662*(1.-g2)*(1.+c*c)/((2.+g2)*pow(1.+g2-2.*g*c,1.5)),"
"dm=0.,"
"dr=0.,"
"ll=0.,"
"bdx=L / 32.,sL;"
""
"vec3 im=vec3(0.),ir=vec3(0.),p=O,Is;"
"vec2 mr;"
"for(int i=0;i < 32;++i){"
"float dx=bdx*(1.+n4(p.xz*2e3).w);"
"p=O+D*(ll+dx);"
"ll+=bdx;"
"mr=SD(p)*dx;"
"dm+=mr.x;"
"dr+=mr.y;"
""
""
""
""
""
"sL=ER(p,_s,R1);"
""
"vec2 dd=Id(p,_s,sL);"
""
"Is=exp(-("
"Km*(dd.x+dm)+"
"Kr*(dd.y+dr)"
"));"
"im+=mr.x*Is;"
"ir+=mr.y*Is;"
"}"
""
"return max(vec3(0.),I*("
"Km*Pm*im+"
"Kr*Pr*ir)"
"+cc*exp(-(Km*dm+Kr*dr)));"
"}"
""
""
""
""
""
""
""
"void main(){"
"vec2 res=vec2(1280.,720.),"
""
"uv=V;uv.x*=res.x/res.y;"
"vec3 C=vec3(0.),ct=vec3(1.),O=_cp+n4(vec2(_t)*fc).xyz*.3,D=normalize(vec3(uv,2.))*_cm,pO,loc;"
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
""
"float f=FAR;"
"pO=O;"
"for(int i=0;i < 3;++i){"
"if(dot(ct,ct)<.001)break;"
"Ce=Cd=Cs=vec3(0.);"
"RT(O,D,f);"
""
""
"if(hm > 0){"
"loc=Ce;"
"O=hp+hn*EPS;"
""
"vec3 cd=Cd,cs=Cs,chi=hi,chn=hn,chp=hp;"
"cell_t cc=c;"
"float chl=hl,"
"shl=RT(O,_s,100.);"
"Cd=cd;Cs=cs;hn=chn;hp=chp;hi=chi;c=cc;hl=chl;"
"if(shl > 100.)loc+=brdf(_s)*S(O,_s,ER(O,_s,R1),vec3(I));"
"C+=ct*S(pO,D,hl,loc);"
"D=ref();"
"ct*=brdf(D);"
"f*=.6;"
"}else{"
"C+=ct*S(O,D,ER(O,D,R1),vec3(0.));"
"break;"
"}"
"}"
""
"gl_FragColor=vec4(C,1.);"
"}"
, 
"void main(){"
"vec2 uv=fc/_r;"
"if(_p < 1.)"
"gl_FragColor=vec4(mix(0.,step(uv.x,_p),step(uv.y,.025)));"
"else "
"gl_FragColor=pow(texture2D(_F,uv,-20.)*.7/32.,vec4(1./2.2));"
""
""
""
""
"}"
, 
""
""
""
""
"uniform float _t,_p,_pt;"
"uniform vec2 _r;"
"uniform vec3 _s,_cp;"
"uniform mat3 _cm;"
"uniform sampler2D _N,_T,_P,_F;"
"varying vec2 V;"
"vec2 fc=floor(gl_FragCoord.xy);"
"vec4 n4(vec2 v){return texture2D(_N,(v+vec2(.5))/256.,-20.);}"
"float n(vec2 v){return n4(v).w;}"
"float vn(vec2 v,vec2 m){"
"vec2 e=vec2(1.,0.),V=floor(v);v=fract(v);v*=v*(3.-2.*v);"
"return mix(mix(n(mod(V+e.yy,m)),n(mod(V+e.xy,m)),v.x),mix(n(mod(V+e.yx,m)),n(mod(V+e.xx,m)),v.x),v.y);"
"}"
"float fbm(vec2 v,float s){"
"float r=0.,k=.5;"
"for(int i=0;i<12;++i,k*=.5,s*=2.)r+=k*vn(v*s,vec2(s));"
"return r;"
"}"
""
""
"vec4 TT(vec2 p){return texture2D(_T,(p+vec2(.5))/4096.,-20.);}"
"vec4 PP(vec2 p){return texture2D(_P,(floor(p/32.)+vec2(.5))/128.,-20.);}"
, 
};
